### ISSUE TITLE
Slotmachine getting triple bar pays out too much money

### ISSUE THREAD

**Issue by rbrants** [MaikoKingma/DankTimesBot-Plugin-Emoji-Games#8]
The pot gets filled even if the player wins some points back. So when you hit triple bar and get the entire pot you are still generating lots of moneys. 
It might be worth a try to just pay out half the pot on a triple bar to keep things interesting without generating too much money.
This also makes it more interesting if 2 people hit the jackpot in a row. 
pot: 1000
triple bar: 500
2nd triple bar: 250 
ezpz ggwp

**Comment by MaikoKingma** [comment]
Proposed scoring changes:
3 x 7: half pot (max 1000x bet)
3 x bar: quarter pot
3 x lemon: 3x bet
3 x grape: 2x bet
2 x grape: 1x bet
1 x grape 0.5x bet

**Comment by MaikoKingma** [comment]
fixed in b2ce700d4fb4f999c910ab8f9f7a542858b7a410
